name: basabuddy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.12.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  sqflite: ^2.4.1
  csv: ^6.0.0
  connectivity_plus: ^7.0.0
  flutter_tts: 3.8.5
  equatable: ^2.0.8
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg_images/
    - assets/fonts/
    - assets/icons/
    # STORY_ASSETS_START
    - assets/story_pages/05d87818-b7e7-4547-9bd1-519ad6af9a25/
    - assets/story_pages/10efe7f8-1a53-4717-9d8b-cdd50d736fbd/
    - assets/story_pages/18667b4a-ec48-4961-b9db-3fcc87cbea83/
    - assets/story_pages/18ca8bb2-5915-4988-8d2e-bb0b7c6f73a8/
    - assets/story_pages/2b0643d1-1d18-423e-8133-d8b24647254b/
    - assets/story_pages/2ce3e546-10e8-4a72-9334-b94bba0b7b8c/
    - assets/story_pages/3cc95d2b-ebba-4c87-9af9-960bd2f6ae26/
    - assets/story_pages/85489db2-366b-4aba-bfec-d415e07ea58b/
    - assets/story_pages/8e9d748c-e988-45d2-866b-59031ac5b36f/
    - assets/story_pages/927fe3d2-9718-4ada-9e9d-0d70103c7f3f/
    - assets/story_pages/f03b0670-cbc8-467c-906e-c108fad4e429/
    - assets/story_pages/421ff269-859d-455e-a5e7-7b020cdd6984/
    - assets/story_pages/7b49d92b-4cde-4cb9-8032-59563b1099a3/
    - assets/story_pages/4c78f240-dcd3-4444-9bdc-e882b094e7e6/
    - assets/story_pages/fca6ddca-9bbb-4afc-9566-8ff066c7d52e/
    - assets/story_pages/
# STORY_ASSETS_END


    - assets/story_thumbnails/default/
    - assets/story_thumbnails/information/
    - assets/story_thumbnails/narrative/
    - assets/story_thumbnails/vocab/
    - assets/story_thumbnails/teachers_pick/
    - csv_data/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
